---
version: "2"

linters:
  default: all

  disable:
    - wsl
    - depguard
    - noinlineerr
    - exhaustruct

  exclusions:
    paths:
      - mock


  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

    varnamelen:
      ignore-names:
        - id
        - tx
        - fn
        - r
        - i

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  tests: false
