---
profile: tools/cover.out

threshold:
  file: 70
  package: 80
  total: 95

exclude:
  paths:
    - api
    - cmd
    - dash/group.go
    - mariadb
    - meal/error.go
    - mock

force-annotation-comment: true
